trigger:
- main

resources:
- repo: self

variables:
- group: demo-api-secrets
- name: dockerRegistryServiceConnection
  value: 'DockerHubConnection'
- name: imageRepository
  value: 'wakeward/demo-api-app'
- name: containerRegistry
  value: 'docker.io'
- name: dockerfilePath
  value: '$(Build.SourcesDirectory)/Dockerfile'
- name: tag
  value: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Test Go App
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: GoTool@0
      inputs:
        version: '1.24'
    - script: |
        go build -v ./...
        go test -v ./...
      displayName: 'Go Build and Test'

- stage: Docker
  displayName: Build and Push Docker Image
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Docker
    displayName: Docker Build and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)